name: Hotfix Release

on:
  workflow_dispatch:
    inputs:
      hotfix_version:
        description: 'Hotfix version (e.g., 1.0.1)'
        required: true
        type: string
      base_branch:
        description: 'Base branch for hotfix'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - develop
      description:
        description: 'Hotfix description'
        required: true
        type: string

jobs:
  hotfix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create hotfix branch
        run: |
          HOTFIX_BRANCH="hotfix/${{ github.event.inputs.hotfix_version }}"
          git checkout -b $HOTFIX_BRANCH
          echo "hotfix_branch=$HOTFIX_BRANCH" >> $GITHUB_ENV

      - name: Update version to hotfix version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.hotfix_version }} -DgenerateBackupPoms=false
          mvn versions:update-child-modules -DgenerateBackupPoms=false

      - name: Run tests
        run: |
          mvn clean test -Drevision=${{ github.event.inputs.hotfix_version }}

      - name: Build and package
        run: |
          mvn clean package -DskipTests -Drevision=${{ github.event.inputs.hotfix_version }}

      - name: Commit hotfix changes
        run: |
          git add .
          git commit -m "Hotfix: ${{ github.event.inputs.description }} - v${{ github.event.inputs.hotfix_version }}"

      - name: Create hotfix tag
        run: |
          git tag -a "v${{ github.event.inputs.hotfix_version }}" -m "Hotfix release v${{ github.event.inputs.hotfix_version }}: ${{ github.event.inputs.description }}"

      - name: Push hotfix branch and tag
        run: |
          git push origin ${{ env.hotfix_branch }}
          git push origin "v${{ github.event.inputs.hotfix_version }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.hotfix_version }}"
          release_name: "Hotfix v${{ github.event.inputs.hotfix_version }}"
          body: |
            ## 🚨 Hotfix Release v${{ github.event.inputs.hotfix_version }}
            
            ### Description
            ${{ github.event.inputs.description }}
            
            ### Base Branch
            Based on: `${{ github.event.inputs.base_branch }}`
            
            ### Changes
            This is a hotfix release addressing critical issues.
            
            ### Installation
            ```xml
            <dependency>
                <groupId>io.github.gls-athena</groupId>
                <artifactId>athena-parent</artifactId>
                <version>${{ github.event.inputs.hotfix_version }}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            ```
          draft: false
          prerelease: false

      - name: Create Pull Request to merge back
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Merge hotfix v${{ github.event.inputs.hotfix_version }} back to ${{ github.event.inputs.base_branch }}`,
              head: '${{ env.hotfix_branch }}',
              base: '${{ github.event.inputs.base_branch }}',
              body: `
              ## Hotfix Merge Back
            
              This PR merges the hotfix v${{ github.event.inputs.hotfix_version }} back to the ${{ github.event.inputs.base_branch }} branch.
            
              ### Hotfix Details
              - **Version**: v${{ github.event.inputs.hotfix_version }}
              - **Description**: ${{ github.event.inputs.description }}
              - **Base Branch**: ${{ github.event.inputs.base_branch }}
            
              Please review and merge to complete the hotfix process.
              `
            });
            
            console.log(\`Created PR #\${pullRequest.number}\`);

      - name: Deploy hotfix to Maven Repository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          if [ -n "$MAVEN_USERNAME" ] && [ -n "$MAVEN_PASSWORD" ]; then
            mvn deploy -DskipTests -Drevision=${{ github.event.inputs.hotfix_version }} \
              -s .github/settings.xml \
              -Dmaven.repo.username=$MAVEN_USERNAME \
              -Dmaven.repo.password=$MAVEN_PASSWORD
          else
            echo "Maven deployment skipped - credentials not configured"
          fi
